### PR TITLE
SIS Loading schema v1.1 - full spec

### PR DESCRIPTION
**Pull request by karaboldt**
This change brings in v1.1 of the SIS loading schema as a standalone full spec, rather than piecing it together from 1.0 + changes. 

This is half of the work in the [[B2]](https://github.com/unizin/unizin-data-platform/milestone/25) milestone.

### CODE REVIEW

**Comment by unizin-brantlee** [comment]
once finalized, we can utilize a schema diff tool (for example python's `Pyrseas`) to generate migration SQL (which we will need to test and potentially modify).

**Comment by karaboldt** [comment]
Right now this is only documentation - is there something that could diff two HTML files and generate SQL from that?

**Comment by unizin-brantlee** [comment]
not without significant dev work :(

I'm thinking ahead of myself.

**Comment by karaboldt** [comment]
It would save a lot of duplicate work, if only we had the bandwidth to dedicate to decreasing our workload 😄

**Comment by unizin-brantlee** [comment]
perhaps we should "design" in postgres, use a tool to generate docs (at least for a starting point), and a migration (same or different tool). I'll have a look at Pyrseas and see if it can generate appealing HTML docs. Just for options: what we're doing works!

**Comment by pelaprat** [comment]
The 1.1 version of the SIS loading schema does require additions to the UCDM. These will be represented in changes to the [DDL file that creates the core UCDM tables](https://github.com/unizin/udp-schema/blob/master/sql/ddl/010-ucdm-tables.sql), which could form the basis of your diff.

We've also decided to represent SIS loading schemas relationally in the entity store ([see this](https://github.com/unizin/udp-schema/blob/master/sql/ddl/020-ucdm-catalog.sql#L145)), which allows us to automatically gen things like documentation.

**Comment by pelaprat** [comment]
> perhaps we should "design" in postgres, use a tool to generate docs 

This was exactly our intent in representing things like the UCDM, the SIS loading schema, our Canvas Data to UCDM mapping directly in postgres.

**Pull request merged**
